### ISSUE TITLE
ChakraCore and VSCode are missing

### ISSUE THREAD

**Issue by dstorey** [Microsoft/microsoft.github.io#130]
I can't find them in the list or by the search box, so I assume they're not there.

As VSCode is the most popular MS repo, and Chakra already around the 7th most popular, they probably should be in the carousel at the top too.

**Comment by jeffwilcox** [comment]
Thanks for reporting the issue - closing as we've retired this site for the time being.

The newer "open source microsoft" site has a search feature and has sort orders which should bring projects like VSCode to the top, and it'll always be relatively up-to-date.
