### ISSUE TITLE
show carousel indicators depending on number of slides

### ISSUE THREAD

**Issue by alfredbez** [Microsoft/microsoft.github.io#140]
There are currently three slides, but [four indicators](https://github.com/Microsoft/microsoft.github.io/blob/f5474a69db915ba6a0a400b3dff183f7b0e132a7/index.html#L89-L94).

I'd suggest using something like `main.featuredProjects+1`, because n slides ([see](https://github.com/Microsoft/microsoft.github.io/blob/f5474a69db915ba6a0a400b3dff183f7b0e132a7/index.html#L97)) + one [Summary slide](https://github.com/Microsoft/microsoft.github.io/blob/f5474a69db915ba6a0a400b3dff183f7b0e132a7/index.html#L116)

**Comment by shyambabu-kolipaka** [comment]
As per main.js, first all projects are pulling, if the project is in the featured projects list, we are adding to the featuredprojects array. And slides are preparing as per featuredprojects. But, indicator is fixed for 4 indicators. So, if indicator can be added based on number of featured projects, then problem will be solved.

**Comment by jeffwilcox** [comment]
Thanks for reporting the issue - closing as we've retired this site for the time being.
