### ISSUE TITLE
Loading Time

### ISSUE THREAD

**Issue by mohitgupta07** [Microsoft/microsoft.github.io#148]
The data takes some time to load even after the page is loaded once. Caching should be enabled as well gzip-compression must be enabled if possible.

**Comment by jarrydfillmore** [comment]
Agreed.

**Comment by jeffwilcox** [comment]
Thanks for your comments. We are actually revisiting the experience of this underlying site and will be launching an improved experience at opensource.microsoft.com in the future. Thanks for your feedback!
