### ISSUE TITLE
broken C++ Code Analysis link

### ISSUE THREAD

**Issue by japj** [Microsoft/microsoft.github.io#156]
Through a websearch, I found http://microsoft.github.io/CodeAnalysis/ which still exists but has an incorrect link to:

http://microsoft.github.io/CppCodeAnalysis

**Comment by Rupeshiya** [comment]
@japj  Where is the code in which change is required ?? I would like to fix this .

**Comment by ahtee** [comment]
Looks like the link on the webpage is fine. this can be closed

**Comment by Hong-Revo** [comment]
Um, the link is still broken. It's the third "View on GitHub" button at https://microsoft.github.io/CodeAnalysis

**Comment by quasarea** [comment]
@jeffwilcox the third link on that page goes to 404
