### ISSUE TITLE
Improper Padding to the Header in Mobile site

### ISSUE THREAD

**Issue by pranayag** [Microsoft/microsoft.github.io#158]
The header is not properly aligned in the mobile version of site
![microsoft-issue](https://user-images.githubusercontent.com/31480760/46269103-711a1d00-c55c-11e8-98f1-fa528807b82a.PNG)

**Comment by gosaingourav17** [comment]
how exactly should it be?

**Comment by gosaingourav17** [comment]
how exactly do you want it to be?
want to make a pr

**Comment by pranayag** [comment]
Should be equal from both sides and properly aligned.

**Comment by mittalchirag** [comment]
I can make it have proper padding and more responsive. Please, assign it to me.

**Comment by amritsrivastava** [comment]
I'm working on this issue.

**Comment by suhailsinghbains** [comment]
Hi, Can I please work on this issue, I am new here

**Comment by Sai-Adarsh** [comment]
I'm interested with this issue. I'll get started and will give a PR.

**Comment by Sai-Adarsh** [comment]
> I guess we cannot solve it from this Repo, there is some JS code that is been run.

That's cool. :)

**Comment by jeffwilcox** [comment]
Sorry, that web site is not open source at this time (ironically, I agree). We are working to improve the site...

**Comment by umran16** [comment]
Yeniyim
