### ISSUE TITLE
have a js framework for microsoft

### ISSUE THREAD

**Issue by javadbat** [microsoft/microsoft.github.io#181]
today's google and facebook have their own js framework like react and angular and backed and help them to grow and create a community for their js framework.
but react is not good due to complex workflow with redux and nonstandard jsx file and angular use typescript and it really heavy and of course need compile that make it really useless.
why Microsoft don't support aurelia and great Rob Eisenberg and systemjs to build a great community for Microsoft.

**Comment by jeffwilcox** [comment]
Thanks for the feedback - I am closing this issue for the time being. I know many Microsoft teams that make use of React, Angular, and Aurelia... I think we very much want our teams and engineers to be able to help work to support any and all JavaScript frameworks.
