### ISSUE TITLE
Broken Link - microsoft.github.io

### ISSUE THREAD

**Issue by CoconutMacaroon** [microsoft/microsoft.github.io#182]
In the file, `README.md`, the link `microsoft.github.io` does not work. It goes to GitHub's 404 page. I suggest that the text is unlinked.

**Comment by WesleyM77** [comment]
another broken link in that file is opensource.microsoft.com at it's giving an error 502.

**Comment by CoconutMacaroon** [comment]
> another broken link in that file is opensource.microsoft.com at it's giving an error 502.

Where is that? For me, when I copy-paste that link into my browser, it works normally.

**Comment by jeffwilcox** [comment]
There was a short Kubernetes outage earlier today. Closing. Thanks for reporting though!

**Comment by CoconutMacaroon** [comment]
I get that the `502` error was an outage, but what about the `404` error in `README.md`. Can this be re-opened until that is also fixed?

**Comment by deidyomega** [comment]
`[microsoft.github.io](microsoft.github.io)` should be changed to 

`[microsoft.github.io](https://microsoft.github.io)`
