### ISSUE TITLE
Nothing showing in "Recent Contributions" section

### ISSUE THREAD

**Issue by JennJin** [microsoft/microsoft.github.io#209]
The "Recent Contributions" section on https://opensource.microsoft.com/ecosystem/ doesn't appear to have any content. I know Microsoft is sharing OS content, so please share. :-)

![Recent Contributions](https://user-images.githubusercontent.com/3375924/108449619-9f295600-7218-11eb-93de-a879019ed37b.png)

**Comment by jeffwilcox** [comment]
This no longer looks to be an issue.
