### ISSUE TITLE
Joining Organization ...

### ISSUE THREAD

**Issue by hegdepavankumar** [microsoft/microsoft.github.io#223]
Is any chance to join the community ...currently, I am doing My internship in Capgemini I just want to contribute to open source...is any chance please let me join this community...
this is my profile and My recent Contributions: - https://github.com/hegdepavankumar

**Comment by jeffwilcox** [comment]
Hi @hegdepavankumar - you can contribute to any Microsoft open source project, whether opening issues, participating in discussions and code reviews, or opening pull requests with contributions. No need to join an organization to do this.
