### ISSUE TITLE
Clean up the footer

### ISSUE THREAD

**Issue by ipavl** [Microsoft/microsoft.github.io#55]
Currently, it looks like there are three separate "footers" on the page. The first two (with the light blue and the bolder blue backgrounds) aren't bad, but the third (white background) makes the layout look "broken" since it switches back to a white background, has a smaller width than the second one, and has a lot of content that looks like it was randomly tossed together.

A larger (single) footer, such as the one on microsoft.com, might work better than the current "second" and "third" footers, but it really depends on how the content is organized.

The open source line (the `credits` div) also stands out since it's much longer than anything else in that section, and it also bumps the content on the right side of the footer down so that it is no longer even with the content on the left. It could possibly be placed after the "Microsoft"-esque footer, and maybe centered on the page.

**Comment by kkirsche** [comment]
@martinwoodward Are the colors from an internal style guide or would you be open to a pull request with a rework that addresses the issue with the white footer following the colored ones?

**Comment by capfei** [comment]
@Snesha Fixed some issues with #93

**Comment by kkirsche** [comment]
Were there other people pulls associated to this? Or just closing due to age?

**Comment by R3V07T** [comment]
N30

**Comment by kkirsche** [comment]
What about November 30th?

**Comment by jeffwilcox** [comment]
Kevin, we're closing these out due to age mostly, there's a larger effort to launch a more dynamic index of Microsoft Open Source over at https://opensource.microsoft.com, instead of the rather manual updates that were happening to this site in the past.

Do let us know if anything here seems super urgent!

**Comment by kkirsche** [comment]
Sounds good. Thanks for the information. I'll look over this tonight!
