### ISSUE TITLE
+ hompage links please

### ISSUE THREAD

**Issue by tomByrer** [Microsoft/microsoft.github.io#65]
Most MS projects have their own "homepage" (eg http://www.typescriptlang.org/ & http://reactive-extensions.github.io/RxJS/ ) but sadly, they aren't listed.  Might be slightly better to change the header to the homepage, but either way, an icon for each like the [upper-right project icons here](http://www.jsdelivr.com/) would be ideal.

**Comment by jeffwilcox** [comment]
Thanks for reporting the issue - closing as we've retired this site for the time being.

Good points on the project homepages - we're looking to get more of these indexed on the newer site as we can.
