### ISSUE TITLE
Could we open source Microsoft Bob?

### ISSUE THREAD

**Issue by PunkChameleon** [Microsoft/microsoft.github.io#7]
It's orphaned, and could be fun to put out there! Seriously!

https://en.wikipedia.org/wiki/Microsoft_Bob

**Comment by jnievele** [comment]
Bob introduced a LOT more than just Comic Sans... without Bob, we'd never have seen Clippy. 

Maybe the time is right for Bob 2.0, with Clippy (or Rover, or Scuzz) powered by the AI that normally calls herself Cortana...
