### ISSUE TITLE
Contributing Problem

### ISSUE THREAD

**Issue by sahilbabbar** [Microsoft/microsoft.github.io#79]
This website is not based on any framework like Bootstrap or Foundation and therefore, it is difficult for the developers like me who don't know whats going on in the present code. So, why not shift to a framework which will also enable universal contributions and good features also.

**Comment by martinwoodward** [comment]
It does use Bootstrap (and Angular), but the CSS was pulled from a standard corporate template and could definitely be easier to use. We also take your point about making contribution easier - not just in the code but in the PR flow etc. I'll take a look into what we can do to make it easier to contribute, if you have any ideas let me know.

**Comment by sahilbabbar** [comment]
Thanks.

According to me, to enable easy contribution, there should be a wiki page that should have all the details of the CSS Classes used, their purpose with their respective properties(preferably in tabular form). This will enormously speed up the contribution as well as increase readability. For PR Flow, the contributors should be encouraged to put screenshots of previous HTML page and the new HTML page made by them; to clearly see the difference. Also, one of the basic thing is comments in code, clear and descriptive comments.
