### ISSUE TITLE
Opensource Windows Services for UNIX

### ISSUE THREAD

**Issue by schrepfler** [Microsoft/microsoft.github.io#87]
One of the key reasons one would choose a platform other than Windows is that a massive chunk of the OSS stack working under things like Cygwin or natively compiled libraries is very often a minefield of bugs and incompatibilities. Reviving Windows Services for UNIX would be a Jujutsu move and hopefully one which can switch some users back to Windows for professional work which requires a stable *nix-like toolchain.

**Comment by Perfectionista** [comment]
what about... No? Why disregard a tool? Why put in many manhours to port something to something you don't need? Why do you NEED Windows? Why don't you just dualboot? Why don't you just port it yourself?

**Comment by schrepfler** [comment]
This ticket can be closed as MS released Windows Subsystem for Linux now. I'm pretty sure that validates the ticket so I won't answer the questions.
