### ISSUE TITLE
Code is free and available on your favorite platform

### ISSUE THREAD

**Issue by mattl** [Microsoft/microsoft.github.io#88]
I'm not sure this is the best place for issues, apologies. @martinwoodward -- Is the source for Code published somewhere? Will it be? 

It'd be great to package it up and get it in various package managers. Does Microsoft have a place that would host Debian packages?

**Comment by martinwoodward** [comment]
No worries @mattl, sorry for the delay - are you referring to the source for the microsoft.github.io site or the source for the .NET Core etc (and is that what you are talking about regarding hosting of Debian packages?)  For .NET see https://github.com/dotnet/coreclr/blob/master/README.md#get-net-core - we are actively working on making it much easier to get running. Still very early...

**Comment by mattl** [comment]
Hey, I'm actually referring to "Visual Studio Code" -- https://code.visualstudio.com/

**Comment by martinwoodward** [comment]
Ah right sorry. Suggest you vote here:

http://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7755573-open-source-vs-code

Martin.

**Comment by mattl** [comment]
Thanks

**Comment by mattl** [comment]
Happy to see this finally happened :)

**Comment by PixleProgrambetaxl** [comment]
+1
