### ISSUE TITLE
IE, Spartan specific warnings informing unmet security conditions.

### ISSUE THREAD

**Issue by sudheesh001** [Microsoft/microsoft.github.io#95]
1. SEC7115: :visited and :link styles can only differ by color. Some styles were not applied to :visited.
2. HTML1409: Invalid attribute name character. Attribute names should not contain ("),('),(<), or (=).
3. HTML1423: Malformed start tag. Attributes should be separated by whitespace.

Reference to : https://msdn.microsoft.com/query/dev12.query?appId=Dev12IDEF1&l=EN-US&k=k(VS.WebClient.Help.SEC7115)

**Comment by Snesha** [comment]
Fixed with PR #129
