### ISSUE TITLE
Footer text overlaps on small screen sizes

### ISSUE THREAD

**Issue by sudheesh001** [Microsoft/microsoft.github.io#97]
### Actual Result
Additional to #80 
![screen shot 2015-05-27 at 13 15 39](https://cloud.githubusercontent.com/assets/4545925/7831380/e7b5f306-0473-11e5-8d9d-0e188968a4d9.png)

### Expected results:
There should be a small gap between the text and the bottom footer left aligned images.

**Comment by jack71** [comment]
:+1:

**Comment by roy128** [comment]
:+1:

**Comment by blackHawk777** [comment]
Check this pull request for this issue 
https://github.com/Microsoft/microsoft.github.io/pull/123
